name: Build usvfs-fuse

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  VCPKG_BINARY_SOURCES: ${{ vars.AZ_BLOB_VCPKG_URL != '' && format('clear;x-azblob,{0},{1},readwrite', vars.AZ_BLOB_VCPKG_URL, secrets.AZ_BLOB_SAS) || '' }}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      # set VCPKG Root
      - name: "Set environmental variables"
        run: |
          echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Configure usvfs-fuse build
        run: |
          cmake --preset linux "-DCMAKE_INSTALL_PREFIX=install"

      - name: Build usvfs-fuse
        run: cmake --build build --config RelWithDebInfo

      - name: Install usvfs-fuse
        run: cmake --install build --config RelWithDebInfo

      - name: Upload usvfs-fuse artifact
        uses: actions/upload-artifact@master
        with:
          name: usvfs-fuse
          path: ./install
